### ISSUE TITLE
ConfigTransformation' (1.0.5) is using deprecated task execution handler

### ISSUE THREAD

**Issue by RoyceLithgo** [sbabaei/Vsts#13]
##[section]Starting: ConfigTransformation 
==============================================================================
Task         : Config Transformation
Description  : Easy and fast transform your xml based configuration files
Version      : 1.0.5
Author       : Saeid Babaei
Help         : [More Information](https://github.com/sbabaei/Vsts/blob/master/ConfigTransformation/overview.md)
==============================================================================
##[warning]Task 'ConfigTransformation' (1.0.5) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib
Preparing task execution handler.
Executing the powershell script: d:\a\_tasks\ConfigTransformation_ea0af5c0-9b4e-11e6-b1b5-7b777069d24a\1.0.5\ConfigTransform.ps1
##[section]Finishing: ConfigTransformation

**Comment by aahue1889** [comment]
Running into same issue:

##[warning]Task 'ConfigTransformation' (1.0.5) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib
Preparing task execution handler.
Executing the powershell script: D:\a\_tasks\ConfigTransformation_ea0af5c0-9b4e-11e6-b1b5-7b777069d24a\1.0.5\ConfigTransform.ps1
##[ Microsoft.Web.XmlTransform.XmlNodeException: Could not resolve 'UserDatabase' as a type of Transform ---> Microsoft.Web.XmlTransform.XmlTransformationException: Could not resolve 'UserDatabase' as a type of Transform
   at Microsoft.Web.XmlTransform.NamedTypeFactory.Construct[ObjectType](String typeName)
   at Microsoft.Web.XmlTransform.XmlElementContext.CreateObjectFromAttribute[ObjectType](String& argumentString, XmlAttribute& objectAttribute)
   --- End of inner exception stack trace ---
   at Microsoft.Web.XmlTransform.XmlTransformationLogger.LogErrorFromException(Exception ex)
   at Microsoft.Web.XmlTransform.XmlTransformation.Apply(XmlDocument xmlTarget)
   at CallSite.Target(Closure , CallSite , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
   at CallSite.Target(Closure , CallSite , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

**Comment by BrandonSchreck** [comment]
Having similar issue
